name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry pyinstaller
        python -m poetry install --no-root
    - name: Build binary
      run: |
        python -m poetry run pyinstaller -F -c --clean --name file-backup -i src/shell32_172.ico --hidden-import src.backend.local --hidden-import src.backend.server --hidden-import src.backend.baidu --noupx main.py
    - uses: actions/upload-artifact@v3
      with:
        name: file-backup_ubuntu
        path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry pyinstaller
        python -m poetry install --no-root
    - name: Build binary
      run: |
        python -m poetry run pyinstaller -F -c --clean --name file-backup -i src/shell32_172.ico --hidden-import src.backend.local --hidden-import src.backend.server --hidden-import src.backend.baidu --noupx main.py
    - uses: actions/upload-artifact@v3
      with:
        name: file-backup_windows
        path: dist/
